[project]
name = "a2a-multiple-agents-on-single-host"
version = "0.1.0"
description = "Run multiple agents on single host using A2A protocol."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk>=0.3.1",
    "google-adk>=1.11.0",
]
