// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: instruction.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "itk";

export interface Instruction {
  /** what should the "agent" do */
  step?: { $case: "callAgent"; value: CallAgent } | { $case: "returnResponse"; value: ReturnResponse } | {
    $case: "steps";
    value: SeriesOfSteps;
  } | undefined;
}

/** gets the agent card from a remote agent, calls it and returns the response */
export interface CallAgent {
  /** which transport use to get agent card and later call */
  transport: string;
  /** where to get the agent card from */
  agentCardUri: string;
  /** instruction for the called agent */
  instruction:
    | Instruction
    | undefined;
  /** whether to use streaming */
  streaming: boolean;
}

/** this option just returns a response */
export interface ReturnResponse {
  /** what to return to the calling agent */
  response: string;
}

/** executes step series and returns response based on response_generator */
export interface SeriesOfSteps {
  instructions: Instruction[];
  responseGenerator: SeriesOfSteps_ResponseGenerator;
}

export enum SeriesOfSteps_ResponseGenerator {
  /** RESPONSE_GENERATOR_UNSPECIFIED - default */
  RESPONSE_GENERATOR_UNSPECIFIED = 0,
  RESPONSE_GENERATOR_CONCAT = 1,
  UNRECOGNIZED = -1,
}

export function seriesOfSteps_ResponseGeneratorFromJSON(object: any): SeriesOfSteps_ResponseGenerator {
  switch (object) {
    case 0:
    case "RESPONSE_GENERATOR_UNSPECIFIED":
      return SeriesOfSteps_ResponseGenerator.RESPONSE_GENERATOR_UNSPECIFIED;
    case 1:
    case "RESPONSE_GENERATOR_CONCAT":
      return SeriesOfSteps_ResponseGenerator.RESPONSE_GENERATOR_CONCAT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SeriesOfSteps_ResponseGenerator.UNRECOGNIZED;
  }
}

export function seriesOfSteps_ResponseGeneratorToJSON(object: SeriesOfSteps_ResponseGenerator): string {
  switch (object) {
    case SeriesOfSteps_ResponseGenerator.RESPONSE_GENERATOR_UNSPECIFIED:
      return "RESPONSE_GENERATOR_UNSPECIFIED";
    case SeriesOfSteps_ResponseGenerator.RESPONSE_GENERATOR_CONCAT:
      return "RESPONSE_GENERATOR_CONCAT";
    case SeriesOfSteps_ResponseGenerator.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseInstruction(): Instruction {
  return { step: undefined };
}

export const Instruction: MessageFns<Instruction> = {
  encode(message: Instruction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.step?.$case) {
      case "callAgent":
        CallAgent.encode(message.step.value, writer.uint32(10).fork()).join();
        break;
      case "returnResponse":
        ReturnResponse.encode(message.step.value, writer.uint32(18).fork()).join();
        break;
      case "steps":
        SeriesOfSteps.encode(message.step.value, writer.uint32(26).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Instruction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstruction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.step = { $case: "callAgent", value: CallAgent.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.step = { $case: "returnResponse", value: ReturnResponse.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.step = { $case: "steps", value: SeriesOfSteps.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Instruction {
    return {
      step: isSet(object.callAgent)
        ? { $case: "callAgent", value: CallAgent.fromJSON(object.callAgent) }
        : isSet(object.call_agent)
        ? { $case: "callAgent", value: CallAgent.fromJSON(object.call_agent) }
        : isSet(object.returnResponse)
        ? { $case: "returnResponse", value: ReturnResponse.fromJSON(object.returnResponse) }
        : isSet(object.return_response)
        ? { $case: "returnResponse", value: ReturnResponse.fromJSON(object.return_response) }
        : isSet(object.steps)
        ? { $case: "steps", value: SeriesOfSteps.fromJSON(object.steps) }
        : undefined,
    };
  },

  toJSON(message: Instruction): unknown {
    const obj: any = {};
    if (message.step?.$case === "callAgent") {
      obj.callAgent = CallAgent.toJSON(message.step.value);
    } else if (message.step?.$case === "returnResponse") {
      obj.returnResponse = ReturnResponse.toJSON(message.step.value);
    } else if (message.step?.$case === "steps") {
      obj.steps = SeriesOfSteps.toJSON(message.step.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Instruction>, I>>(base?: I): Instruction {
    return Instruction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Instruction>, I>>(object: I): Instruction {
    const message = createBaseInstruction();
    switch (object.step?.$case) {
      case "callAgent": {
        if (object.step?.value !== undefined && object.step?.value !== null) {
          message.step = { $case: "callAgent", value: CallAgent.fromPartial(object.step.value) };
        }
        break;
      }
      case "returnResponse": {
        if (object.step?.value !== undefined && object.step?.value !== null) {
          message.step = { $case: "returnResponse", value: ReturnResponse.fromPartial(object.step.value) };
        }
        break;
      }
      case "steps": {
        if (object.step?.value !== undefined && object.step?.value !== null) {
          message.step = { $case: "steps", value: SeriesOfSteps.fromPartial(object.step.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseCallAgent(): CallAgent {
  return { transport: "", agentCardUri: "", instruction: undefined, streaming: false };
}

export const CallAgent: MessageFns<CallAgent> = {
  encode(message: CallAgent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transport !== "") {
      writer.uint32(10).string(message.transport);
    }
    if (message.agentCardUri !== "") {
      writer.uint32(18).string(message.agentCardUri);
    }
    if (message.instruction !== undefined) {
      Instruction.encode(message.instruction, writer.uint32(26).fork()).join();
    }
    if (message.streaming !== false) {
      writer.uint32(32).bool(message.streaming);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallAgent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallAgent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transport = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.agentCardUri = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.instruction = Instruction.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.streaming = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallAgent {
    return {
      transport: isSet(object.transport) ? globalThis.String(object.transport) : "",
      agentCardUri: isSet(object.agentCardUri)
        ? globalThis.String(object.agentCardUri)
        : isSet(object.agent_card_uri)
        ? globalThis.String(object.agent_card_uri)
        : "",
      instruction: isSet(object.instruction) ? Instruction.fromJSON(object.instruction) : undefined,
      streaming: isSet(object.streaming) ? globalThis.Boolean(object.streaming) : false,
    };
  },

  toJSON(message: CallAgent): unknown {
    const obj: any = {};
    if (message.transport !== "") {
      obj.transport = message.transport;
    }
    if (message.agentCardUri !== "") {
      obj.agentCardUri = message.agentCardUri;
    }
    if (message.instruction !== undefined) {
      obj.instruction = Instruction.toJSON(message.instruction);
    }
    if (message.streaming !== false) {
      obj.streaming = message.streaming;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallAgent>, I>>(base?: I): CallAgent {
    return CallAgent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallAgent>, I>>(object: I): CallAgent {
    const message = createBaseCallAgent();
    message.transport = object.transport ?? "";
    message.agentCardUri = object.agentCardUri ?? "";
    message.instruction = (object.instruction !== undefined && object.instruction !== null)
      ? Instruction.fromPartial(object.instruction)
      : undefined;
    message.streaming = object.streaming ?? false;
    return message;
  },
};

function createBaseReturnResponse(): ReturnResponse {
  return { response: "" };
}

export const ReturnResponse: MessageFns<ReturnResponse> = {
  encode(message: ReturnResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.response !== "") {
      writer.uint32(10).string(message.response);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReturnResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReturnResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.response = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReturnResponse {
    return { response: isSet(object.response) ? globalThis.String(object.response) : "" };
  },

  toJSON(message: ReturnResponse): unknown {
    const obj: any = {};
    if (message.response !== "") {
      obj.response = message.response;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReturnResponse>, I>>(base?: I): ReturnResponse {
    return ReturnResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReturnResponse>, I>>(object: I): ReturnResponse {
    const message = createBaseReturnResponse();
    message.response = object.response ?? "";
    return message;
  },
};

function createBaseSeriesOfSteps(): SeriesOfSteps {
  return { instructions: [], responseGenerator: 0 };
}

export const SeriesOfSteps: MessageFns<SeriesOfSteps> = {
  encode(message: SeriesOfSteps, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.instructions) {
      Instruction.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.responseGenerator !== 0) {
      writer.uint32(16).int32(message.responseGenerator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SeriesOfSteps {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSeriesOfSteps();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instructions.push(Instruction.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.responseGenerator = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SeriesOfSteps {
    return {
      instructions: globalThis.Array.isArray(object?.instructions)
        ? object.instructions.map((e: any) => Instruction.fromJSON(e))
        : [],
      responseGenerator: isSet(object.responseGenerator)
        ? seriesOfSteps_ResponseGeneratorFromJSON(object.responseGenerator)
        : isSet(object.response_generator)
        ? seriesOfSteps_ResponseGeneratorFromJSON(object.response_generator)
        : 0,
    };
  },

  toJSON(message: SeriesOfSteps): unknown {
    const obj: any = {};
    if (message.instructions?.length) {
      obj.instructions = message.instructions.map((e) => Instruction.toJSON(e));
    }
    if (message.responseGenerator !== 0) {
      obj.responseGenerator = seriesOfSteps_ResponseGeneratorToJSON(message.responseGenerator);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SeriesOfSteps>, I>>(base?: I): SeriesOfSteps {
    return SeriesOfSteps.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SeriesOfSteps>, I>>(object: I): SeriesOfSteps {
    const message = createBaseSeriesOfSteps();
    message.instructions = object.instructions?.map((e) => Instruction.fromPartial(e)) || [];
    message.responseGenerator = object.responseGenerator ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
