FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o agent .

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/agent .

EXPOSE 9999

CMD ["./agent"]
