version: '3.8'

services:
  hello-world-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AZURE_AI_FOUNDRY_PROJECT_ENDPOINT=${AZURE_AI_FOUNDRY_PROJECT_ENDPOINT}
      - AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME=${AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
    volumes:
      - ~/.azure:/home/appuser/.azure:ro  # Mount Azure CLI credentials
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
