---
name: Lint Code Base
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  lint:
    name: Lint Code Base (${{ matrix.project_dir }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir:
          - samples/python/
          - demo/ui/
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Get Changed Python Files in ${{ matrix.project_dir }}
        id: get-changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=d \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} \
            -- ${{ matrix.project_dir }} \
            | sed "s#^${{ matrix.project_dir }}##g" \
            | paste -sd " " -)

          echo "Detected changed files in ${{ matrix.project_dir }}:"
          echo "$CHANGED_FILES"

          echo "filtered_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: uv sync --dev
        working-directory: ${{ matrix.project_dir }}

      - name: Run Ruff Linter
        if: steps.get-changed-files.outputs.filtered_files != ''
        run: uv run ruff check ${{ steps.get-changed-files.outputs.filtered_files }}
        working-directory: ${{ matrix.project_dir }}

      - name: Run Ruff Format Check
        if: steps.get-changed-files.outputs.filtered_files != ''
        run: uv run ruff format --check ${{ steps.get-changed-files.outputs.filtered_files }}
        working-directory: ${{ matrix.project_dir }}

      - name: Run MyPy Type Checker
        if: steps.get-changed-files.outputs.filtered_files != ''
        run: uv run mypy ${{ steps.get-changed-files.outputs.filtered_files }}
        working-directory: ${{ matrix.project_dir }}

      - name: Run Pyright (Pylance equivalent)
        if: steps.get-changed-files.outputs.filtered_files != ''
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: ${{ matrix.project_dir }}
          files: ${{ steps.get-changed-files.outputs.filtered_files }}
